<?xml version="1.0" encoding="utf-8"?><Database Name="quanlysinhvien" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Quy-Laptop\SQLEXPRESS;Initial Catalog=quanlysinhvien;Persist Security Info=True;User ID=sa;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="QuanLySinhVien.Properties.Settings" SettingsPropertyName="quanlysinhvienConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Lop" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="LopHoc_SinhVien" Member="LopHoc" ThisKey="Lop" OtherKey="MaLop" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="MaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaoVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="LopHoc_SinhVien" Member="SinhViens" ThisKey="MaLop" OtherKey="Lop" Type="SinhVien" />
    </Type>
  </Table>
</Database>